import React, { Component } from 'react';
import axios from 'axios';

import DataTable from './DataTable.jsx';

import totalCost from '../../../helpers/totalCost.js';

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      investmentData: [],
      totalCost: 0,
    };
  }

  componentDidMount() {
    axios.get(
      'https://gist.githubusercontent.com/cranium/d8b83184bf0750f2c834760b7c9203dc/raw/a73a70716951f77b90e84b8848ff1fee46938dd1/soi.json'
    ).then((response) => {
      this.setState({
        investmentData: response.data,
        totalCost: totalCost(response.data),
      });
    }).catch((error) => {
      console.log(error);
    });
  }

  render() {
    const { investmentData, totalCost } = this.state;
    return (
      <div>
        <p>Krakatoa Venture Fund I, LP</p>
        <p>As of 11/19/2018 · Generated by Fred's Administrator (admin @eshareinc.com) @ 11/19/2018 11:58:23</p>
        <DataTable 
          investmentData={investmentData}
        />
      </div>
    );
  }
}

export default App;
