import React, { Component } from 'react';
import axios from 'axios';

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      investmentData: null
    };
  }

  componentDidMount() {
    axios.get(
      'https://gist.githubusercontent.com/cranium/d8b83184bf0750f2c834760b7c9203dc/raw/a73a70716951f77b90e84b8848ff1fee46938dd1/soi.json'
      ).then((response) => {
        this.setState({
          investmentData: response.data
        })
      }).catch((error) => {
        console.log(error);
      })
  }

  render() {
    return (
      <div>
        <p>Krakatoa Venture Fund I, LP</p>
        <p>As of 11/19/2018 · Generated by Fred's Administrator (admin @eshareinc.com) @ 11/19/2018 11:58:23</p>

        <table>
          <tbody>
            <tr>
              <th>Investment</th>
              <th>Asset</th>
              <th>Investment date</th>
              <th>Shares</th>
              <th>Cost</th>
            </tr>
          </tbody>
        </table>

      </div>
    )
  }
}

export default App;
