import React from 'react';

import styles from '../../../styles/Description.css';

const Description = () => (
  <div className={styles.container}>
    <p>Krakatoa Venture Fund I, LP</p>
    <p>As of 11/19/2018 · Generated by Fred's Administrator (admin @eshareinc.com) @ 11/19/2018 11:58:23</p>
  </div>
);

export default Description;
